//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbCoderOmEntities : DbContext
    {
        public DbCoderOmEntities()
            : base("name=DbCoderOmEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AboutDetailsTbl> AboutDetailsTbls { get; set; }
        public virtual DbSet<AdminTbl> AdminTbls { get; set; }
        public virtual DbSet<ProjectsTbl> ProjectsTbls { get; set; }
    }
}
