//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Portfolio.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectsTbl
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Subtitle { get; set; }
        public string Detail { get; set; }
        public string Image1 { get; set; }
        public string Image2 { get; set; }
        public string Clientname { get; set; }
        public string Year { get; set; }
        public string Framework { get; set; }
        public string LiveLink { get; set; }
        public Nullable<bool> status { get; set; }
        public Nullable<System.DateTime> rts { get; set; }
        public string GithubLink { get; set; }
    }
}
